# Generated by Django 4.1.2 on 2022-10-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank='True', upload_to='', verbose_name='Фото')),
                ('picture_description', models.CharField(max_length=150, verbose_name='Описание картины')),
                ('picture_data', models.DateTimeField(blank=True)),
            ],
        ),
    ]
