# Generated by Django 4.1.2 on 2022-12-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0003_otzivy_alter_mainpage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='otzivy',
            name='avatar',
            field=models.ImageField(blank='True', upload_to='photos/%Y/%m/%d/', verbose_name='Выберите фото для аватара'),
        ),
        migrations.AlterField(
            model_name='otzivy',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Как вас зовут?'),
        ),
        migrations.AlterField(
            model_name='otzivy',
            name='otziv',
            field=models.TextField(blank=True, verbose_name='Ваш отзыв'),
        ),
    ]
