# Generated by Django 4.1.2 on 2022-12-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0004_otzivy_avatar_alter_otzivy_name_alter_otzivy_otziv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otzivy',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='picture_description',
            field=models.CharField(blank='True', max_length=150, verbose_name='Описание картины'),
        ),
    ]
